# Site settings

title: Jekyll Theme - Lazy
description: It is minimal and lazy!
email: boykopk@gmail.com

baseurl: "/jekyll-theme-lazy" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: docs

twitter_username: jekyllrb
github_username:  boykopk

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - docs
  - node_modules
  - scss
